format = """
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$sudo\
$character"""

[directory]
read_only = ""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](blue)"

[git_branch]
format = '\[[$symbol$branch]($style)'
symbol = ""
style = "bright-black"

[git_state]
format = '\([$state($progress_current/$progress_total)]($style)\)'
style = "bright-black"

[git_status]
format = '[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)\]'
style = "bright-black"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[python]
format = "[$virtualenv]($style) "

